// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzDaoLKmWrso4FTXLaCVtHR04KGKVHag',
    appId: '1:866128814740:web:962d054c82fbb963bdca81',
    messagingSenderId: '866128814740',
    projectId: 'shortsmap-1',
    authDomain: 'shortsmap-1.firebaseapp.com',
    storageBucket: 'shortsmap-1.firebasestorage.app',
    measurementId: 'G-P2K7Q6F5LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCII5flAtQpIt-q5k4TqdN-38qzQUZ4Ac4',
    appId: '1:866128814740:android:a3a1405e9ebb2bccbdca81',
    messagingSenderId: '866128814740',
    projectId: 'shortsmap-1',
    storageBucket: 'shortsmap-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXrSirfT2LWHxrMEJTWoGfVdirRPhGrnY',
    appId: '1:866128814740:ios:5e5b518e46fc552dbdca81',
    messagingSenderId: '866128814740',
    projectId: 'shortsmap-1',
    storageBucket: 'shortsmap-1.firebasestorage.app',
    iosBundleId: 'com.example.shortsRestaurant',
  );
}
